### ISSUE TITLE
Remove sensitive data

### ISSUE THREAD

**Issue by geetha-rangaswamaiah** [huntertran/ptidej-wordcloud#2]
Hi @huntertran 
Your https://github.com/huntertran/ptidej-wordcloud/blob/master/data/scrapy/kapua.txt file contains my official email id in the following lines.
8917, 8939, 9020, 9040, 9481.
Kindly remove those lines from the repo for security concerns.
Thank you.

**Comment by huntertran** [comment]
I crawl the data from the Kapua project in eclipse IoT, there is a link to the Github repo, which you use the email to sign off the commit.
When you use that, the email was published, and everyone can see it. To avoid it, I think you should use a Github generated email for commit.
More info here: https://dev.to/codewithfahad/github-tip-of-the-day-keep-your-commit-email-address-private-2eo2

**Comment by geetha-rangaswamaiah** [comment]
@huntertran thank you for the info. I will ensure this for my future commits.
My Organisation security team is asking me to request for the removal of those lines that contain my email id from your file.
Could you please remove them?

**Comment by huntertran** [comment]
The point is that this is an auto-generated file. Even if I remove it now, it will be there next time the code run.
However, I could manually delete the email

**Comment by geetha-rangaswamaiah** [comment]
I see. Thank you @huntertran 
Every time the file is generated will you be removing the email id right? Or maybe you can make the code to do that. 
Because when the security team finds that my email id is exposed again then they'll contact me again and I'll have to reach out to you once again for the same reason.
I appreciate your understanding.

**Comment by huntertran** [comment]
The file is deleted
